import { QUESTIONNAIRE_SCHEMA_VERSION } from '../constants/schema-version';
import type { QuestionnaireSchemaDto } from './schema.types';

/** Default seed content for active questionnaire definition (Question Engine). */
export const QUESTIONNAIRE_SEED: QuestionnaireSchemaDto = {
  schemaVersion: QUESTIONNAIRE_SCHEMA_VERSION,
  totalSteps: 10,
  steps: [
    {
      id: 'goal',
      stepNumber: 1,
      title: 'What do you want to become?',
      subtitle:
        "You can choose one or more. We'll build your roadmap from here.",
      selection: 'multi',
      uiKind: 'options',
      reviewLabel: 'Goal',
      reviewIcon: 'target',
      // Only roles with active role_recipes in the learning catalog.
      options: [
        {
          value: 'front-end-developer',
          label: 'Front End Developer',
          icon: 'code',
          iconClassName: 'bg-arc-green-100 text-arc-green-600',
        },
        {
          value: 'marketing-specialist',
          label: 'Marketing Specialist',
          icon: 'megaphone',
          iconClassName: 'bg-arc-purple-100 text-arc-purple-600',
        },
      ],
    },
    {
      id: 'motivation',
      stepNumber: 2,
      title: 'Why is this important to you?',
      subtitle: 'Select all that apply.',
      selection: 'multi',
      allowOther: true,
      uiKind: 'options',
      reviewLabel: 'Why',
      reviewIcon: 'mountain',
      options: [
        { value: 'career', label: 'Better career opportunities' },
        { value: 'income', label: 'Higher income' },
        { value: 'growth', label: 'Personal growth' },
        { value: 'satisfaction', label: 'Job satisfaction' },
        { value: 'meaningful', label: 'Work on meaningful projects' },
      ],
    },
    {
      id: 'currentJob',
      stepNumber: 3,
      title: 'What is your current job?',
      subtitle: 'Select the option that best describes you.',
      selection: 'single',
      allowOther: true,
      uiKind: 'options',
      reviewLabel: 'Current Job',
      reviewIcon: 'briefcase',
      options: [
        { value: 'student', label: 'Student' },
        { value: 'employed-related', label: 'Employed – related field' },
        { value: 'employed-unrelated', label: 'Employed – unrelated field' },
        { value: 'freelancer', label: 'Freelancer' },
        { value: 'not-working', label: 'Not working' },
      ],
    },
    {
      id: 'skills',
      stepNumber: 4,
      title: 'What skills do you already have?',
      subtitle: 'Select all that apply.',
      selection: 'multi',
      allowOther: true,
      uiKind: 'options',
      reviewLabel: 'Skills',
      reviewIcon: 'bar-chart',
      options: [
        { value: 'excel', label: 'Excel / Google Sheets' },
        { value: 'sql', label: 'SQL' },
        { value: 'python', label: 'Python' },
        { value: 'javascript', label: 'JavaScript' },
        { value: 'html-css', label: 'HTML / CSS' },
        { value: 'data-viz', label: 'Data Visualization' },
        { value: 'communication', label: 'Communication' },
        { value: 'marketing-seo', label: 'Marketing / SEO' },
        { value: 'none', label: 'None of the above' },
      ],
    },
    {
      id: 'studyHours',
      stepNumber: 5,
      title: 'How many hours per week can you dedicate to learning?',
      subtitle: 'Select one option.',
      selection: 'single',
      uiKind: 'options',
      reviewLabel: 'Study Time',
      reviewIcon: 'clock',
      options: [
        { value: 'lt-3', label: 'Less than 3 hours' },
        { value: '3-5', label: '3–5 hours' },
        { value: '5-8', label: '5–8 hours' },
        { value: '8-12', label: '8–12 hours' },
        { value: 'gt-12', label: 'More than 12 hours' },
      ],
    },
    {
      id: 'schedule',
      stepNumber: 6,
      title: 'What days or times work best for you?',
      subtitle: 'Select all that apply.',
      selection: 'multi',
      uiKind: 'schedule',
      reviewLabel: 'Best Time',
      reviewIcon: 'calendar',
      options: [],
      scheduleDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      scheduleTimes: [
        { value: 'morning', label: 'Morning (6 AM – 12 PM)' },
        { value: 'afternoon', label: 'Afternoon (12 PM – 5 PM)' },
        { value: 'evening', label: 'Evening (5 PM – 10 PM)' },
        { value: 'late-night', label: 'Late Night (10 PM – 2 AM)' },
      ],
    },
    {
      id: 'deadline',
      stepNumber: 7,
      title: 'What is your target deadline?',
      subtitle: 'Select one option.',
      selection: 'single',
      uiKind: 'options',
      reviewLabel: 'Deadline',
      reviewIcon: 'clock',
      options: [
        { value: '1-3', label: '1–3 months' },
        { value: '3-6', label: '3–6 months' },
        { value: '6-12', label: '6–12 months' },
        { value: '12+', label: '12+ months' },
        { value: 'none', label: 'No specific deadline' },
      ],
    },
    {
      id: 'learningStyle',
      stepNumber: 8,
      title: 'What learning style do you prefer?',
      subtitle: 'Select all that apply.',
      selection: 'multi',
      allowOther: true,
      uiKind: 'options',
      reviewLabel: 'Learning Style',
      reviewIcon: 'graduation-cap',
      options: [
        { value: 'doing', label: 'Learn by doing (Projects)' },
        { value: 'videos', label: 'Watch & learn (Videos)' },
        { value: 'reading', label: 'Read & understand' },
        { value: 'quizzes', label: 'Interactive quizzes' },
        { value: 'guides', label: 'Follow step-by-step guides' },
      ],
    },
    {
      id: 'confidence',
      stepNumber: 9,
      title: 'What is your confidence level right now?',
      subtitle: 'Select one option.',
      selection: 'single',
      uiKind: 'options',
      reviewLabel: 'Confidence Level',
      reviewIcon: 'bar-chart',
      options: [
        { value: 'starting', label: 'Just getting started', icon: 'sparkles' },
        { value: 'beginner', label: 'Beginner', icon: 'smile' },
        { value: 'somewhat', label: 'Somewhat confident', icon: 'zap' },
        { value: 'confident', label: 'Confident', icon: 'flame' },
        { value: 'very', label: 'Very confident', icon: 'rocket' },
      ],
    },
    {
      id: 'quitReasons',
      stepNumber: 10,
      title: 'What has made you quit learning before?',
      subtitle: 'Select all that apply.',
      selection: 'multi',
      allowOther: true,
      uiKind: 'options',
      reviewLabel: 'Challenges',
      reviewIcon: 'shield',
      options: [
        { value: 'time', label: 'Lack of time' },
        { value: 'motivation', label: 'Lost motivation' },
        { value: 'information', label: 'Too much information' },
        { value: 'direction', label: 'No clear direction' },
        { value: 'overwhelming', label: 'Too hard / Overwhelming' },
      ],
    },
  ],
};
