import { QUESTIONNAIRE_SCHEMA_VERSION } from '../constants/schema-version';
import type { QuestionnaireSchemaDto } from './schema.types';

/** Default seed content for active questionnaire definition (v4 learner profiling). */
export const QUESTIONNAIRE_SEED: QuestionnaireSchemaDto = {
  schemaVersion: QUESTIONNAIRE_SCHEMA_VERSION,
  totalSteps: 10,
  steps: [
    {
      id: 'goal',
      stepNumber: 1,
      title: 'What do you want to learn or become?',
      subtitle:
        'Select all that apply; first pick is your primary track.',
      selection: 'multi',
      allowOther: false,
      uiKind: 'track-select',
      reviewLabel: 'Track',
      reviewIcon: 'target',
      // Domain options injected at runtime from UnitsCatalogService.
      options: [],
    },
    {
      id: 'motivation',
      stepNumber: 2,
      title: 'Why is this important to you?',
      subtitle: 'Select all that apply.',
      selection: 'multi',
      allowOther: true,
      uiKind: 'options',
      reviewLabel: 'Why',
      reviewIcon: 'mountain',
      options: [
        {
          value: 'change_career',
          label: 'Change career',
          profileHint: 'motivation',
        },
        {
          value: 'perform_better',
          label: 'Perform better in my current job',
          profileHint: 'motivation',
        },
        {
          value: 'get_promoted',
          label: 'Get promoted',
          profileHint: 'motivation',
        },
        {
          value: 'build_portfolio',
          label: 'Build a portfolio',
          profileHint: 'motivation',
        },
        {
          value: 'prepare_interviews',
          label: 'Prepare for interviews',
          profileHint: 'motivation',
        },
        {
          value: 'personal_interest',
          label: 'Learn for personal interest',
          profileHint: 'motivation',
        },
        { value: 'earn_more', label: 'Earn more', profileHint: 'motivation' },
      ],
    },
    {
      id: 'currentContext',
      stepNumber: 3,
      title: 'What is your current work or study situation?',
      subtitle: 'Tell us your situation and how often you use this subject.',
      selection: 'single',
      allowOther: true,
      uiKind: 'context',
      reviewLabel: 'Context',
      reviewIcon: 'briefcase',
      options: [
        { value: 'student', label: 'Student' },
        { value: 'employed', label: 'Employed' },
        { value: 'unemployed', label: 'Not working' },
        { value: 'career_switcher', label: 'Career switcher' },
        { value: 'freelancer', label: 'Freelancer' },
      ],
      secondaryOptions: [
        { value: 'never_used', label: 'Never used this subject' },
        { value: 'personal_projects', label: 'Personal exploration only' },
        { value: 'studied_before', label: 'Studied it before / took a course' },
        { value: 'work_sometimes', label: 'Use it sometimes at work' },
        { value: 'work_regularly', label: 'Use it regularly at work' },
      ],
    },
    {
      id: 'skills',
      stepNumber: 4,
      title: 'Which skills do you already have?',
      subtitle:
        'Select skills, then rate how independently you can use each one.',
      selection: 'multi',
      allowOther: true,
      uiKind: 'skill-evidence',
      reviewLabel: 'Skills',
      reviewIcon: 'bar-chart',
      options: [
        { value: 'html-css', label: 'HTML / CSS' },
        { value: 'javascript', label: 'JavaScript' },
        { value: 'typescript', label: 'TypeScript' },
        { value: 'react', label: 'React' },
        { value: 'git', label: 'Git' },
        { value: 'sql', label: 'SQL' },
        { value: 'python', label: 'Python' },
        { value: 'excel', label: 'Excel / Google Sheets' },
        { value: 'data-viz', label: 'Data Visualization' },
        { value: 'communication', label: 'Communication' },
      ],
      exposureOptions: [
        { value: 'heard_of', label: 'Heard of it' },
        { value: 'follow_with_help', label: 'Can follow with help' },
        { value: 'use_independently', label: 'Can use independently' },
        { value: 'use_professionally', label: 'Use professionally' },
      ],
    },
    {
      id: 'selfStage',
      stepNumber: 5,
      title: 'Which description best matches your current level?',
      subtitle: 'Be honest — we place you carefully and never skip proof.',
      selection: 'single',
      uiKind: 'options',
      reviewLabel: 'Level',
      reviewIcon: 'bar-chart',
      options: [
        {
          value: '1',
          label: 'Beginner — new / start from basics',
          profileHint: 'stage:1',
        },
        {
          value: '2',
          label: 'Medium — basic ideas, still needs guidance',
          profileHint: 'stage:2',
        },
        {
          value: '3',
          label: 'Pro — standard tasks independently',
          profileHint: 'stage:3',
        },
        {
          value: '4',
          label: 'Advanced — complex problems and projects',
          profileHint: 'stage:4',
        },
        {
          value: '5',
          label: 'Job-ready Specialist — professional results',
          profileHint: 'stage:5',
        },
      ],
    },
    {
      id: 'studyHours',
      stepNumber: 6,
      title: 'How much time can you realistically study each week?',
      subtitle: 'Pick a weekly range and preferred session length.',
      selection: 'single',
      uiKind: 'capacity',
      reviewLabel: 'Study Time',
      reviewIcon: 'clock',
      options: [
        { value: 'lt-3', label: 'Less than 3 hours' },
        { value: '3-5', label: '3–5 hours' },
        { value: '5-8', label: '5–8 hours' },
        { value: '8-12', label: '8–12 hours' },
        { value: 'gt-12', label: 'More than 12 hours' },
      ],
      sessionOptions: [
        { value: '25', label: '25 minutes' },
        { value: '45', label: '45 minutes' },
        { value: '60', label: '60 minutes' },
        { value: '90', label: '90 minutes' },
      ],
    },
    {
      id: 'schedule',
      stepNumber: 7,
      title: 'Which times of day normally work best?',
      subtitle: 'Used for reminders and weekly pacing — not calendar invites.',
      selection: 'multi',
      uiKind: 'schedule',
      reviewLabel: 'Best Time',
      reviewIcon: 'calendar',
      options: [],
      scheduleDays: [],
      scheduleTimes: [
        { value: 'morning', label: 'Morning (6 AM – 12 PM)' },
        { value: 'afternoon', label: 'Afternoon (12 PM – 5 PM)' },
        { value: 'evening', label: 'Evening (5 PM – 10 PM)' },
        { value: 'late-night', label: 'Late Night (10 PM – 2 AM)' },
      ],
    },
    {
      id: 'targetOutcome',
      stepNumber: 8,
      title: 'What result do you want, and when?',
      subtitle: 'Outcome sets your target stage. Deadline only changes pace.',
      selection: 'single',
      uiKind: 'outcome',
      reviewLabel: 'Outcome',
      reviewIcon: 'flag',
      options: [
        {
          value: 'understand_basics',
          label: 'Understand the basics',
          profileHint: 'targetStage:2',
        },
        {
          value: 'use_independently',
          label: 'Use skills independently',
          profileHint: 'targetStage:3',
        },
        {
          value: 'build_advanced',
          label: 'Build advanced real projects',
          profileHint: 'targetStage:4',
        },
        {
          value: 'job_ready',
          label: 'Become job-ready / change career',
          profileHint: 'targetStage:5',
        },
      ],
      secondaryOptions: [
        { value: '1-3', label: '1–3 months' },
        { value: '3-6', label: '3–6 months' },
        { value: '6-12', label: '6–12 months' },
        { value: '12+', label: '12+ months' },
        { value: 'none', label: 'No specific deadline' },
      ],
    },
    {
      id: 'learningStyle',
      stepNumber: 9,
      title: 'How do you learn best?',
      subtitle: 'Biases lesson format — never removes required practice.',
      selection: 'multi',
      allowOther: false,
      uiKind: 'options',
      reviewLabel: 'Learning Style',
      reviewIcon: 'graduation-cap',
      options: [
        {
          value: 'doing',
          label: 'Hands-on practice',
          profileHint: 'style:doing',
        },
        {
          value: 'guides',
          label: 'Guided examples',
          profileHint: 'style:guides',
        },
        { value: 'videos', label: 'Video', profileHint: 'style:videos' },
        { value: 'audio', label: 'Audio', profileHint: 'style:audio' },
        { value: 'reading', label: 'Reading', profileHint: 'style:reading' },
        { value: 'quizzes', label: 'Quizzes', profileHint: 'style:quiz' },
        { value: 'projects', label: 'Projects', profileHint: 'style:doing' },
      ],
    },
    {
      id: 'barriers',
      stepNumber: 10,
      title: 'How confident are you, and what usually gets in the way?',
      subtitle:
        'Confidence calibrates placement. Barriers shape coaching only.',
      selection: 'multi',
      allowOther: true,
      uiKind: 'confidence-barriers',
      reviewLabel: 'Confidence & Barriers',
      reviewIcon: 'shield',
      options: [
        {
          value: 'starting',
          label: 'Just getting started',
          profileHint: 'confidence',
        },
        {
          value: 'beginner',
          label: 'Beginner confidence',
          profileHint: 'confidence',
        },
        {
          value: 'somewhat',
          label: 'Somewhat confident',
          profileHint: 'confidence',
        },
        { value: 'confident', label: 'Confident', profileHint: 'confidence' },
        { value: 'very', label: 'Very confident', profileHint: 'confidence' },
      ],
      secondaryOptions: [
        { value: 'lack_of_time', label: 'Lack of time' },
        { value: 'unclear_plan', label: 'Unclear plan' },
        { value: 'too_difficult', label: 'Content too difficult' },
        { value: 'too_easy', label: 'Content too easy' },
        { value: 'motivation_drops', label: 'Motivation drops' },
        { value: 'interruptions', label: 'Interruptions' },
        { value: 'fear_of_failure', label: 'Fear of failure' },
        { value: 'language_difficulty', label: 'Language difficulty' },
      ],
    },
  ],
};
