import {
  NotificationCategory,
  NotificationType,
} from './entities/notification.entity';

/** Settings UI toggle ids — keep in sync with arc-app settings. */
export const PreferenceToggleIds = [
  'push',
  'email',
  'learningReminders',
  'weeklyProgress',
  'streakReminders',
  'rewards',
  'social',
  'studyTogetherInvites',
  'battleInvites',
  'leagueUpdates',
  'luckyWheel',
  'coachMessages',
  'marketing',
] as const;

export type PreferenceToggleId = (typeof PreferenceToggleIds)[number];

export const DEFAULT_PREFERENCES: Record<PreferenceToggleId, boolean> = {
  push: true,
  email: true,
  learningReminders: true,
  weeklyProgress: true,
  streakReminders: true,
  rewards: true,
  social: true,
  studyTogetherInvites: true,
  battleInvites: true,
  leagueUpdates: true,
  luckyWheel: true,
  coachMessages: true,
  marketing: false,
};

export const TYPE_CATEGORY: Record<NotificationType, NotificationCategory> = {
  [NotificationType.StudyReminder]: NotificationCategory.Learning,
  [NotificationType.StudyStarting]: NotificationCategory.Learning,
  [NotificationType.MissedSession]: NotificationCategory.Learning,
  [NotificationType.ReplanSuggestion]: NotificationCategory.Coach,
  [NotificationType.DeadlineRisk]: NotificationCategory.Learning,
  [NotificationType.PaceAhead]: NotificationCategory.Learning,
  [NotificationType.PaceBehind]: NotificationCategory.Learning,
  [NotificationType.StreakRisk]: NotificationCategory.Streak,
  [NotificationType.StreakProtected]: NotificationCategory.Streak,
  [NotificationType.StreakBroken]: NotificationCategory.Streak,
  [NotificationType.StreakRecovered]: NotificationCategory.Streak,
  [NotificationType.WeeklyRecap]: NotificationCategory.System,
  [NotificationType.MissedWeekRecovery]: NotificationCategory.Coach,
  [NotificationType.RewardGranted]: NotificationCategory.Rewards,
  [NotificationType.BadgeUnlocked]: NotificationCategory.Rewards,
  [NotificationType.RankClose]: NotificationCategory.Rewards,
  [NotificationType.RankUnlocked]: NotificationCategory.Rewards,
  [NotificationType.RankGateCompleted]: NotificationCategory.Rewards,
  [NotificationType.ChestReady]: NotificationCategory.Rewards,
  [NotificationType.LuckyWheelReady]: NotificationCategory.Rewards,
  [NotificationType.LuckyWheelReward]: NotificationCategory.Rewards,
  [NotificationType.FriendRequest]: NotificationCategory.Social,
  [NotificationType.FriendRequestAccepted]: NotificationCategory.Social,
  [NotificationType.NewFollower]: NotificationCategory.Social,
  [NotificationType.StudyInvite]: NotificationCategory.Social,
  [NotificationType.StudyInviteAccepted]: NotificationCategory.Social,
  [NotificationType.StudySessionStarting]: NotificationCategory.Social,
  [NotificationType.StudyPartnerReady]: NotificationCategory.Social,
  [NotificationType.StudySessionCompleted]: NotificationCategory.Social,
  [NotificationType.StudySessionMissed]: NotificationCategory.Social,
  [NotificationType.BattleInvite]: NotificationCategory.Social,
  [NotificationType.BattleInviteExpiring]: NotificationCategory.Social,
  [NotificationType.BattleAccepted]: NotificationCategory.Social,
  [NotificationType.BattleStarting]: NotificationCategory.Social,
  [NotificationType.BattleResult]: NotificationCategory.Rewards,
  [NotificationType.BattleRematch]: NotificationCategory.Social,
  [NotificationType.LeagueUpdate]: NotificationCategory.Social,
  [NotificationType.LeagueStarted]: NotificationCategory.Social,
  [NotificationType.LeaguePositionChanged]: NotificationCategory.Social,
  [NotificationType.LeaguePromotionRisk]: NotificationCategory.Social,
  [NotificationType.LeagueDemoteRisk]: NotificationCategory.Social,
  [NotificationType.LeaguePositionRisk]: NotificationCategory.Social,
  [NotificationType.LeagueFinalized]: NotificationCategory.Social,
  [NotificationType.LeaguePromoted]: NotificationCategory.Social,
  [NotificationType.LeagueDemoted]: NotificationCategory.Social,
  [NotificationType.LeagueGateBlocked]: NotificationCategory.Social,
  [NotificationType.Referral]: NotificationCategory.Social,
  [NotificationType.ProductUpdate]: NotificationCategory.System,
  [NotificationType.CoachMessage]: NotificationCategory.Coach,
  [NotificationType.ChatMessage]: NotificationCategory.Social,
  [NotificationType.System]: NotificationCategory.System,
  [NotificationType.Security]: NotificationCategory.System,
};

/** Which preference gate blocks creating this notification type. */
export const TYPE_PREFERENCE_GATE: Partial<
  Record<NotificationType, PreferenceToggleId>
> = {
  [NotificationType.StudyReminder]: 'learningReminders',
  [NotificationType.StudyStarting]: 'learningReminders',
  [NotificationType.MissedSession]: 'learningReminders',
  [NotificationType.DeadlineRisk]: 'learningReminders',
  [NotificationType.PaceAhead]: 'learningReminders',
  [NotificationType.PaceBehind]: 'learningReminders',
  [NotificationType.StreakRisk]: 'streakReminders',
  [NotificationType.StreakProtected]: 'streakReminders',
  [NotificationType.StreakBroken]: 'streakReminders',
  [NotificationType.StreakRecovered]: 'streakReminders',
  [NotificationType.WeeklyRecap]: 'weeklyProgress',
  [NotificationType.MissedWeekRecovery]: 'coachMessages',
  [NotificationType.ReplanSuggestion]: 'coachMessages',
  [NotificationType.RewardGranted]: 'rewards',
  [NotificationType.BadgeUnlocked]: 'rewards',
  [NotificationType.RankClose]: 'rewards',
  [NotificationType.RankUnlocked]: 'rewards',
  [NotificationType.RankGateCompleted]: 'rewards',
  [NotificationType.ChestReady]: 'rewards',
  [NotificationType.LuckyWheelReady]: 'luckyWheel',
  [NotificationType.LuckyWheelReward]: 'luckyWheel',
  [NotificationType.FriendRequest]: 'social',
  [NotificationType.FriendRequestAccepted]: 'social',
  [NotificationType.NewFollower]: 'social',
  [NotificationType.ChatMessage]: 'social',
  [NotificationType.StudyInvite]: 'studyTogetherInvites',
  [NotificationType.StudyInviteAccepted]: 'studyTogetherInvites',
  [NotificationType.StudySessionStarting]: 'studyTogetherInvites',
  [NotificationType.StudyPartnerReady]: 'studyTogetherInvites',
  [NotificationType.StudySessionCompleted]: 'studyTogetherInvites',
  [NotificationType.StudySessionMissed]: 'studyTogetherInvites',
  [NotificationType.BattleInvite]: 'battleInvites',
  [NotificationType.BattleInviteExpiring]: 'battleInvites',
  [NotificationType.BattleAccepted]: 'battleInvites',
  [NotificationType.BattleStarting]: 'battleInvites',
  [NotificationType.BattleRematch]: 'battleInvites',
  [NotificationType.LeagueUpdate]: 'leagueUpdates',
  [NotificationType.LeagueStarted]: 'leagueUpdates',
  [NotificationType.LeaguePositionChanged]: 'leagueUpdates',
  [NotificationType.LeaguePromotionRisk]: 'leagueUpdates',
  [NotificationType.LeagueDemoteRisk]: 'leagueUpdates',
  [NotificationType.LeaguePositionRisk]: 'leagueUpdates',
  [NotificationType.LeagueFinalized]: 'leagueUpdates',
  [NotificationType.LeaguePromoted]: 'leagueUpdates',
  [NotificationType.LeagueDemoted]: 'leagueUpdates',
  [NotificationType.LeagueGateBlocked]: 'leagueUpdates',
  [NotificationType.CoachMessage]: 'coachMessages',
  [NotificationType.ProductUpdate]: 'marketing',
};

/** Relative app paths allowed in actionUrl (prefix match after normalize). */
export const ACTION_URL_ALLOWLIST = [
  '/home',
  '/learn',
  '/week',
  '/roadmap',
  '/league',
  '/leagues',
  '/battle',
  '/friends',
  '/social',
  '/study',
  '/chat',
  '/profile',
  '/rewards',
  '/rank',
  '/wallet',
  '/settings',
  '/inbox',
  '/notifications',
  '/chest',
  '/lucky-wheel',
  '/referral',
] as const;

export const DAILY_PUSH_SOFT_CAP = 8;
