import type { UnitsJsonDocument } from './units-json.types';

/**
 * Downloadable import example — one skill chain + one unit of every
 * lesson_type showing each content shape.
 */
export const EXAMPLE_UNITS_DOCUMENT: UnitsJsonDocument = {
  $schema_notes:
    'Flattened content pool. skills_index = prerequisite DAG (namespaced slug ids). units = self-describing lessons; content shape depends on lesson_type. Import at /admin/units → Import JSON.',
  skills_index: [
    {
      id: 'example-stack:basics',
      title: 'Example Basics',
      prerequisites: [],
      level: 1,
    },
    {
      id: 'example-stack:advanced',
      title: 'Example Advanced',
      prerequisites: ['example-stack:basics'],
      level: 2,
    },
  ],
  units: [
    {
      id: 'example-basics-read',
      title: 'Reading unit example',
      skills_taught: ['example-stack:basics'],
      prerequisites: [],
      level: 1,
      estimated_minutes: 20,
      formats: ['reading'],
      lesson_type: 'reading',
      domain: 'frontend',
      stack: 'example-stack',
      provider: 'MDN',
      url: 'https://developer.mozilla.org/',
      xp: 35,
      content: {
        objective: 'What the learner should understand after reading.',
        sections: [
          'First topic covered in this reading',
          'Second topic covered in this reading',
        ],
        keyTakeaways: ['One-line takeaway learners must remember'],
      },
    },
    {
      id: 'example-basics-video',
      title: 'Video unit example',
      skills_taught: ['example-stack:basics'],
      prerequisites: [],
      level: 1,
      estimated_minutes: 15,
      formats: ['videos'],
      lesson_type: 'video',
      domain: 'frontend',
      stack: 'example-stack',
      provider: 'web.dev',
      url: 'https://web.dev/',
      xp: 30,
      content: {
        objective: 'What the video teaches.',
        note: 'What to watch for while viewing.',
      },
    },
    {
      id: 'example-basics-practice',
      title: 'Practice unit example',
      skills_taught: ['example-stack:basics'],
      prerequisites: [],
      level: 1,
      estimated_minutes: 40,
      formats: ['doing'],
      lesson_type: 'practice',
      domain: 'frontend',
      stack: 'example-stack',
      provider: 'MDN',
      url: 'https://developer.mozilla.org/',
      xp: 60,
      content: {
        objective: 'What the learner builds.',
        task: 'Concrete build instruction for the learner.',
        acceptanceCriteria: [
          'First checkable acceptance criterion',
          'Second checkable acceptance criterion',
        ],
        hints: ['Optional hint shown on demand'],
        starterHtml: '<div class="starter">optional starter markup</div>',
      },
    },
    {
      id: 'example-basics-quiz',
      title: 'Quiz unit example',
      skills_taught: ['example-stack:basics'],
      prerequisites: [],
      level: 1,
      estimated_minutes: 10,
      formats: ['quiz'],
      lesson_type: 'quiz',
      domain: 'frontend',
      stack: 'example-stack',
      provider: 'MDN',
      url: 'https://developer.mozilla.org/',
      xp: 25,
      content: {
        objective: 'What the quiz confirms.',
        passScore: 2,
        questions: [
          {
            q: 'Multiple choice question text?',
            type: 'mcq',
            options: ['Wrong option', 'Correct option', 'Wrong option'],
            answer: 1,
            explain: 'Optional explanation shown after answering.',
          },
          {
            q: 'True/false question text.',
            type: 'boolean',
            answer: true,
          },
        ],
      },
    },
    {
      id: 'example-advanced-project',
      title: 'Mini project unit example',
      skills_taught: ['example-stack:advanced'],
      prerequisites: ['example-stack:basics'],
      level: 2,
      estimated_minutes: 90,
      formats: ['doing'],
      lesson_type: 'mini_project',
      domain: 'frontend',
      stack: 'example-stack',
      provider: 'CSS-Tricks',
      url: 'https://css-tricks.com/',
      xp: 120,
      content: {
        objective: 'End-to-end build combining prior skills.',
        task: 'Project brief for the learner.',
        acceptanceCriteria: ['Criterion 1', 'Criterion 2', 'Criterion 3'],
      },
    },
    {
      id: 'example-advanced-interactive',
      title: 'Interactive unit example',
      skills_taught: ['example-stack:advanced'],
      prerequisites: ['example-stack:basics'],
      level: 2,
      estimated_minutes: 30,
      formats: ['interactive', 'doing'],
      lesson_type: 'interactive',
      domain: 'frontend',
      stack: 'example-stack',
      provider: 'Codepip',
      url: 'https://flexboxfroggy.com/',
      xp: 50,
      content: {
        objective: 'What the external interactive exercise practices.',
        task: 'What to complete on the external site.',
        acceptanceCriteria: ['All levels solved'],
      },
    },
  ],
};
