import type { UnitsJsonDocument } from './units-json.types';

/**
 * Downloadable import example — one skill chain + one unit of every
 * lesson_type showing each content shape.
 */
export const EXAMPLE_UNITS_DOCUMENT: UnitsJsonDocument = {
  $schema_notes:
    'Flattened content pool. skills_index = prerequisite DAG (namespaced slug ids). units = self-describing lessons; content shape depends on lesson_type. Import at /admin/units → Import JSON.',
  skills_index: [
    {
      id: 'example-stack:basics',
      title: 'Example Basics',
      prerequisites: [],
      level: 1,
    },
    {
      id: 'example-stack:advanced',
      title: 'Example Advanced',
      prerequisites: ['example-stack:basics'],
      level: 2,
    },
  ],
  units: [
    {
      id: 'example-basics-read',
      title: 'Reading unit example',
      skills_taught: ['example-stack:basics'],
      prerequisites: [],
      level: 1,
      estimated_minutes: 20,
      formats: ['reading'],
      lesson_type: 'reading',
      domain: 'frontend',
      stack: 'example-stack',
      provider: 'MDN',
      url: 'https://developer.mozilla.org/',
      xp: 35,
      content: {
        objective: 'What the learner should understand after reading.',
        sections: [
          'First topic covered in this reading',
          'Second topic covered in this reading',
        ],
        keyTakeaways: ['One-line takeaway learners must remember'],
      },
    },
    {
      id: 'example-basics-video',
      title: 'Video unit example',
      skills_taught: ['example-stack:basics'],
      prerequisites: [],
      level: 1,
      estimated_minutes: 15,
      formats: ['videos'],
      lesson_type: 'video',
      domain: 'frontend',
      stack: 'example-stack',
      provider: 'web.dev',
      url: 'https://web.dev/',
      xp: 30,
      content: {
        objective: 'What the video teaches.',
        note: 'What to watch for while viewing.',
      },
    },
    {
      id: 'example-basics-practice',
      title: 'Practice unit example',
      skills_taught: ['example-stack:basics'],
      prerequisites: [],
      level: 1,
      estimated_minutes: 40,
      formats: ['doing'],
      lesson_type: 'practice',
      domain: 'frontend',
      stack: 'example-stack',
      provider: 'MDN',
      url: 'https://developer.mozilla.org/',
      xp: 60,
      content: {
        objective: 'What the learner builds.',
        task: 'Concrete build instruction for the learner.',
        acceptanceCriteria: [
          'First checkable acceptance criterion',
          'Second checkable acceptance criterion',
        ],
        hints: ['Optional hint shown on demand'],
        starterHtml: '<div class="starter">optional starter markup</div>',
      },
    },
    {
      id: 'example-basics-quiz',
      title: 'Quiz unit example',
      skills_taught: ['example-stack:basics'],
      prerequisites: [],
      level: 1,
      estimated_minutes: 10,
      formats: ['quiz'],
      lesson_type: 'quiz',
      domain: 'frontend',
      stack: 'example-stack',
      provider: 'MDN',
      url: 'https://developer.mozilla.org/',
      xp: 25,
      content: {
        objective: 'What the quiz confirms.',
        passScore: 2,
        questions: [
          {
            q: 'Multiple choice question text?',
            type: 'mcq',
            options: ['Wrong option', 'Correct option', 'Wrong option'],
            answer: 1,
            explain: 'Optional explanation shown after answering.',
          },
          {
            q: 'True/false question text.',
            type: 'boolean',
            answer: true,
          },
        ],
      },
    },
    {
      id: 'example-advanced-project',
      title: 'Mini project unit example',
      skills_taught: ['example-stack:advanced'],
      prerequisites: ['example-stack:basics'],
      level: 2,
      estimated_minutes: 90,
      formats: ['doing'],
      lesson_type: 'mini_project',
      domain: 'frontend',
      stack: 'example-stack',
      provider: 'CSS-Tricks',
      url: 'https://css-tricks.com/',
      xp: 120,
      content: {
        objective: 'End-to-end build combining prior skills.',
        task: 'Project brief for the learner.',
        acceptanceCriteria: ['Criterion 1', 'Criterion 2', 'Criterion 3'],
      },
    },
    {
      id: 'example-advanced-interactive',
      title: 'Interactive unit example',
      skills_taught: ['example-stack:advanced'],
      prerequisites: ['example-stack:basics'],
      level: 2,
      estimated_minutes: 30,
      formats: ['interactive', 'doing'],
      lesson_type: 'interactive',
      domain: 'frontend',
      stack: 'example-stack',
      provider: 'Codepip',
      url: 'https://flexboxfroggy.com/',
      xp: 50,
      content: {
        objective: 'What the external interactive exercise practices.',
        task: 'What to complete on the external site.',
        acceptanceCriteria: ['All levels solved'],
      },
    },
    {
      id: 'example-basics-scenario',
      title: 'Scenario decision example',
      skills_taught: ['example-stack:basics'],
      prerequisites: [],
      level: 1,
      estimated_minutes: 6,
      formats: ['doing', 'scenario'],
      lesson_type: 'scenario',
      domain: 'frontend',
      stack: 'example-stack',
      xp: 40,
      content: {
        objective: 'Pick the right fix for a broken mobile layout.',
        blocks: [
          {
            type: 'live_context',
            id: 'lc1',
            track_tag: 'frontend',
          },
          {
            type: 'scenario_decision',
            id: 'sd1',
            setup: 'This layout breaks on mobile — flex, grid, or float fix?',
            options: [
              { id: 'opt_flex', label: 'Use flexbox' },
              { id: 'opt_grid', label: 'Use CSS grid' },
              { id: 'opt_float', label: 'Use float' },
            ],
            correctOptionId: 'opt_flex',
            outcomes: {
              opt_flex: 'Flexbox is the right call for this one-dimensional layout.',
              opt_grid: 'Grid works, but flex is simpler here.',
              opt_float: 'Floats are legacy for layout — avoid.',
            },
          },
          {
            type: 'drag_order',
            id: 'do1',
            items: [
              { id: 'a', label: 'Write HTML structure' },
              { id: 'b', label: 'Add CSS rules' },
              { id: 'c', label: 'Test on mobile' },
            ],
            correctOrderHash:
              'a52dd81bfd5e4e66d96b9f598382f6cbf8c5c3897654e6ae9055e03620fcf38e',
            correctOrder: ['a', 'b', 'c'],
            explanation: 'Structure first, then style, then verify.',
          },
        ],
      },
    },
    {
      id: 'example-basics-hotspot',
      title: 'Visual hotspot example',
      skills_taught: ['example-stack:basics'],
      prerequisites: [],
      level: 1,
      estimated_minutes: 5,
      formats: ['doing'],
      lesson_type: 'visual_hotspot',
      domain: 'frontend',
      stack: 'example-stack',
      xp: 35,
      content: {
        objective: 'Tap the element causing layout shift.',
        blocks: [
          {
            type: 'visual_hotspot',
            id: 'vh1',
            imageAssetKey: 'layout-shift-demo-v1',
            hotspots: [
              { id: 'hs_img', label: 'Unsized image', x: 0.3, y: 0.4 },
              { id: 'hs_nav', label: 'Nav bar', x: 0.5, y: 0.1 },
              { id: 'hs_footer', label: 'Footer', x: 0.5, y: 0.9 },
            ],
            correctHotspotId: 'hs_img',
            explanation: 'Images without dimensions cause CLS.',
          },
        ],
      },
    },
    {
      id: 'example-basics-debate',
      title: 'Debate pick example',
      skills_taught: ['example-stack:basics'],
      prerequisites: [],
      level: 1,
      estimated_minutes: 5,
      formats: ['doing'],
      lesson_type: 'debate',
      domain: 'frontend',
      stack: 'example-stack',
      xp: 30,
      content: {
        objective: 'Pick a side in the CSS approach debate.',
        blocks: [
          {
            type: 'debate_pick',
            id: 'db1',
            prompt: 'Which approach for this component library?',
            sideA: 'CSS-in-JS',
            sideB: 'Utility classes',
            preferredSide: 'b',
            feedbackA: 'CSS-in-JS can work but adds runtime cost.',
            feedbackB: 'Utility classes keep the cascade predictable here.',
          },
        ],
      },
    },
    {
      id: 'example-basics-sandbox',
      title: 'Sandbox simulation example',
      skills_taught: ['example-stack:basics'],
      prerequisites: [],
      level: 1,
      estimated_minutes: 10,
      formats: ['doing'],
      lesson_type: 'sandbox_simulation',
      domain: 'frontend',
      stack: 'example-stack',
      xp: 50,
      simulation_asset_key: 'flexbox-mobile-break-v1',
      action_vocabulary: ['use_grid', 'use_flex', 'use_float'],
      content: {
        objective: 'Ship the fix against a stored build snapshot.',
        blocks: [
          {
            type: 'sandbox_simulation',
            id: 'ss1',
            simulationAssetKey: 'flexbox-mobile-break-v1',
            actions: ['use_grid', 'use_flex', 'use_float'],
            correctActions: ['use_flex'],
            outcomeCopy: 'Flexbox fixes the one-dimensional wrap.',
          },
        ],
      },
    },
    {
      id: 'example-marketing-scenario',
      title: 'Marketing CTR scenario',
      skills_taught: ['example-stack:basics'],
      prerequisites: [],
      level: 1,
      estimated_minutes: 6,
      formats: ['doing', 'scenario'],
      lesson_type: 'scenario',
      domain: 'digital-marketing',
      stack: 'campaign-analytics',
      xp: 40,
      content: {
        objective: 'Decide what to do when CTR drops overnight.',
        blocks: [
          {
            type: 'scenario_decision',
            id: 'sd_mkt',
            setup: 'CTR dropped 30% overnight — pause, reallocate, or A/B test?',
            options: [
              { id: 'pause', label: 'Pause spend' },
              { id: 'realloc', label: 'Reallocate budget' },
              { id: 'ab', label: 'A/B test creative' },
            ],
            correctOptionId: 'ab',
            outcomes: {
              pause: 'Pausing stops bleeding but learns nothing.',
              realloc: 'Reallocating without a hypothesis is guesswork.',
              ab: 'A/B testing isolates whether creative caused the drop.',
            },
          },
        ],
      },
    },
  ],
};
