import {
  BadgeCategory,
  BadgeCriteriaType,
  BadgeRarity,
  type BadgeCriteriaJson,
  type BadgeRewardJson,
} from './badge.constants';

export type BadgeSeed = {
  code: string;
  name: string;
  description: string;
  category: BadgeCategory;
  rarity: BadgeRarity;
  iconAssetKey: string;
  criteriaType: BadgeCriteriaType;
  criteriaJson: BadgeCriteriaJson;
  rewardJson: BadgeRewardJson;
  sortOrder: number;
};

export const BADGE_CATALOG_SEED: BadgeSeed[] = [
  {
    code: 'first-step',
    name: 'First Step',
    description: 'Complete the first required lesson.',
    category: BadgeCategory.GettingStarted,
    rarity: BadgeRarity.Common,
    iconAssetKey: 'first-step',
    criteriaType: BadgeCriteriaType.Counter,
    criteriaJson: { counterKey: 'lessons_completed', target: 1 },
    rewardJson: { coins: 25 },
    sortOrder: 1,
  },
  {
    code: 'meet-arlo',
    name: 'Meet Arlo',
    description: 'Complete the AI Goal Interview and save your first roadmap.',
    category: BadgeCategory.GettingStarted,
    rarity: BadgeRarity.Common,
    iconAssetKey: 'first-step',
    criteriaType: BadgeCriteriaType.EventOnce,
    criteriaJson: { eventType: 'roadmap.generated.v1' },
    rewardJson: { coins: 20 },
    sortOrder: 2,
  },
  {
    code: 'plan-builder',
    name: 'Plan Builder',
    description: 'Activate the first weekly plan with at least 2 tasks.',
    category: BadgeCategory.GettingStarted,
    rarity: BadgeRarity.Common,
    iconAssetKey: 'weekly-warrior',
    criteriaType: BadgeCriteriaType.EventOnce,
    criteriaJson: { eventType: 'weekly_plan.activated.v1' },
    rewardJson: { coins: 20 },
    sortOrder: 3,
  },
  {
    code: 'first-full-week',
    name: 'First Full Week',
    description: 'Complete the first weekly commitment.',
    category: BadgeCategory.GettingStarted,
    rarity: BadgeRarity.Uncommon,
    iconAssetKey: 'weekly-warrior',
    criteriaType: BadgeCriteriaType.Counter,
    criteriaJson: { counterKey: 'weeks_completed', target: 1 },
    rewardJson: { coins: 50 },
    sortOrder: 4,
  },
  {
    code: 'lesson-starter',
    name: 'Lesson Starter',
    description: 'Complete 5 required lessons.',
    category: BadgeCategory.Learning,
    rarity: BadgeRarity.Common,
    iconAssetKey: 'first-step',
    criteriaType: BadgeCriteriaType.Counter,
    criteriaJson: { counterKey: 'lessons_completed', target: 5 },
    rewardJson: { coins: 40 },
    sortOrder: 5,
  },
  {
    code: 'lesson-explorer',
    name: 'Lesson Explorer',
    description: 'Complete 25 required lessons.',
    category: BadgeCategory.Learning,
    rarity: BadgeRarity.Uncommon,
    iconAssetKey: 'sql-spark',
    criteriaType: BadgeCriteriaType.Counter,
    criteriaJson: { counterKey: 'lessons_completed', target: 25 },
    rewardJson: { coins: 100 },
    sortOrder: 6,
  },
  {
    code: 'lesson-veteran',
    name: 'Lesson Veteran',
    description: 'Complete 100 required lessons.',
    category: BadgeCategory.Learning,
    rarity: BadgeRarity.Rare,
    iconAssetKey: 'sql-spark',
    criteriaType: BadgeCriteriaType.Counter,
    criteriaJson: { counterKey: 'lessons_completed', target: 100 },
    rewardJson: { coins: 300, gems: 10 },
    sortOrder: 7,
  },
  {
    code: 'format-explorer',
    name: 'Format Explorer',
    description: 'Complete lessons in 5 distinct formats.',
    category: BadgeCategory.Learning,
    rarity: BadgeRarity.Uncommon,
    iconAssetKey: 'sql-spark',
    criteriaType: BadgeCriteriaType.DistinctSet,
    criteriaJson: { setKey: 'lesson_formats', setTarget: 5 },
    rewardJson: { coins: 75 },
    sortOrder: 8,
  },
  {
    code: 'practice-first',
    name: 'Practice First',
    description: 'Complete 10 coding or dataset practices.',
    category: BadgeCategory.Learning,
    rarity: BadgeRarity.Uncommon,
    iconAssetKey: 'project-starter',
    criteriaType: BadgeCriteriaType.Counter,
    criteriaJson: { counterKey: 'practices_completed', target: 10 },
    rewardJson: { coins: 100 },
    sortOrder: 9,
  },
  {
    code: 'deep-learner',
    name: 'Deep Learner',
    description: 'Complete 20 lessons with a meaningful learning action.',
    category: BadgeCategory.Learning,
    rarity: BadgeRarity.Rare,
    iconAssetKey: 'sql-spark',
    criteriaType: BadgeCriteriaType.Counter,
    criteriaJson: { counterKey: 'deep_lessons', target: 20 },
    rewardJson: { coins: 150, gems: 5 },
    sortOrder: 10,
  },
  {
    code: 'quiz-spark',
    name: 'Quiz Spark',
    description: 'Pass the first quiz.',
    category: BadgeCategory.Quiz,
    rarity: BadgeRarity.Common,
    iconAssetKey: 'quiz-crusher',
    criteriaType: BadgeCriteriaType.Counter,
    criteriaJson: { counterKey: 'quizzes_passed', target: 1 },
    rewardJson: { coins: 25 },
    sortOrder: 11,
  },
  {
    code: 'quiz-crusher',
    name: 'Quiz Crusher',
    description: 'Pass 20 unique quizzes.',
    category: BadgeCategory.Quiz,
    rarity: BadgeRarity.Uncommon,
    iconAssetKey: 'quiz-crusher',
    criteriaType: BadgeCriteriaType.Counter,
    criteriaJson: { counterKey: 'quizzes_passed', target: 20 },
    rewardJson: { coins: 100 },
    sortOrder: 12,
  },
  {
    code: 'perfect-checkpoint',
    name: 'Perfect Checkpoint',
    description: 'Score 100% on 10 unique quizzes.',
    category: BadgeCategory.Quiz,
    rarity: BadgeRarity.Rare,
    iconAssetKey: 'quiz-crusher',
    criteriaType: BadgeCriteriaType.Counter,
    criteriaJson: { counterKey: 'perfect_quizzes', target: 10 },
    rewardJson: { coins: 150, gems: 5 },
    sortOrder: 13,
  },
  {
    code: 'challenge-accepted',
    name: 'Challenge Accepted',
    description: 'Pass the first mini challenge.',
    category: BadgeCategory.Quiz,
    rarity: BadgeRarity.Uncommon,
    iconAssetKey: 'quiz-crusher',
    criteriaType: BadgeCriteriaType.Counter,
    criteriaJson: { counterKey: 'challenges_passed', target: 1 },
    rewardJson: { coins: 75 },
    sortOrder: 14,
  },
  {
    code: 'boss-slayer',
    name: 'Boss Slayer',
    description: 'Pass 5 boss challenges at 80%+ without solution reveal.',
    category: BadgeCategory.Quiz,
    rarity: BadgeRarity.Epic,
    iconAssetKey: 'job-ready-eagle',
    criteriaType: BadgeCriteriaType.Counter,
    criteriaJson: { counterKey: 'boss_challenges_passed', target: 5 },
    rewardJson: { coins: 400, gems: 20 },
    sortOrder: 15,
  },
  {
    code: 'weekly-warrior',
    name: 'Weekly Warrior',
    description: 'Complete 2 consecutive weekly commitments.',
    category: BadgeCategory.Consistency,
    rarity: BadgeRarity.Common,
    iconAssetKey: 'weekly-warrior',
    criteriaType: BadgeCriteriaType.Consecutive,
    criteriaJson: { consecutiveKey: 'weekly_streak', minConsecutive: 2 },
    rewardJson: { coins: 50 },
    sortOrder: 16,
  },
  {
    code: 'four-week-flame',
    name: 'Four-Week Flame',
    description: 'Complete 4 consecutive weekly commitments.',
    category: BadgeCategory.Consistency,
    rarity: BadgeRarity.Uncommon,
    iconAssetKey: 'four-week-flame',
    criteriaType: BadgeCriteriaType.Consecutive,
    criteriaJson: { consecutiveKey: 'weekly_streak', minConsecutive: 4 },
    rewardJson: { coins: 125, gems: 5 },
    sortOrder: 17,
  },
  {
    code: 'twelve-week-fire',
    name: 'Twelve-Week Fire',
    description: 'Complete 12 consecutive weekly commitments.',
    category: BadgeCategory.Consistency,
    rarity: BadgeRarity.Rare,
    iconAssetKey: 'four-week-flame',
    criteriaType: BadgeCriteriaType.Consecutive,
    criteriaJson: { consecutiveKey: 'weekly_streak', minConsecutive: 12 },
    rewardJson: { coins: 400, gems: 20 },
    sortOrder: 18,
  },
  {
    code: 'year-of-growth',
    name: 'Year of Growth',
    description: 'Complete 40 weekly commitments in 52 weeks.',
    category: BadgeCategory.Consistency,
    rarity: BadgeRarity.Legendary,
    iconAssetKey: 'four-week-flame',
    criteriaType: BadgeCriteriaType.Counter,
    criteriaJson: { counterKey: 'weeks_completed', target: 40 },
    rewardJson: { coins: 1500, gems: 100, cosmetic: 'frame-year-growth' },
    sortOrder: 19,
  },
  {
    code: 'comeback-eagle',
    name: 'Comeback Eagle',
    description: 'Return after 14+ inactive days and finish a week.',
    category: BadgeCategory.Consistency,
    rarity: BadgeRarity.Rare,
    iconAssetKey: 'comeback-eagle',
    criteriaType: BadgeCriteriaType.EventOnce,
    criteriaJson: { eventType: 'comeback.completed.v1' },
    rewardJson: { coins: 150, gems: 10 },
    sortOrder: 20,
  },
  {
    code: 'roadmap-rookie',
    name: 'Roadmap Rookie',
    description: 'Complete the first roadmap quest.',
    category: BadgeCategory.Roadmap,
    rarity: BadgeRarity.Common,
    iconAssetKey: 'first-step',
    criteriaType: BadgeCriteriaType.Counter,
    criteriaJson: { counterKey: 'quests_completed', target: 1 },
    rewardJson: { coins: 50 },
    sortOrder: 21,
  },
  {
    code: 'phase-finisher',
    name: 'Phase Finisher',
    description: 'Complete the first roadmap phase.',
    category: BadgeCategory.Roadmap,
    rarity: BadgeRarity.Uncommon,
    iconAssetKey: 'sql-spark',
    criteriaType: BadgeCriteriaType.Counter,
    criteriaJson: { counterKey: 'phases_completed', target: 1 },
    rewardJson: { coins: 150, gems: 5 },
    sortOrder: 22,
  },
  {
    code: 'halfway-hero',
    name: 'Halfway Hero',
    description: 'Reach 50% verified roadmap completion.',
    category: BadgeCategory.Roadmap,
    rarity: BadgeRarity.Rare,
    iconAssetKey: 'sql-spark',
    criteriaType: BadgeCriteriaType.Counter,
    criteriaJson: { counterKey: 'roadmap_percent', target: 50 },
    rewardJson: { coins: 300, gems: 15 },
    sortOrder: 23,
  },
  {
    code: 'skill-path-master',
    name: 'Skill Path Master',
    description: 'Complete one full skill path.',
    category: BadgeCategory.Roadmap,
    rarity: BadgeRarity.Epic,
    iconAssetKey: 'job-ready-eagle',
    criteriaType: BadgeCriteriaType.Counter,
    criteriaJson: { counterKey: 'skill_paths_completed', target: 1 },
    rewardJson: { coins: 750, gems: 40 },
    sortOrder: 24,
  },
  {
    code: 'job-ready-eagle',
    name: 'Job-Ready Eagle',
    description: 'Reach final rank with portfolio and interview milestones.',
    category: BadgeCategory.Roadmap,
    rarity: BadgeRarity.Legendary,
    iconAssetKey: 'job-ready-eagle',
    criteriaType: BadgeCriteriaType.Composite,
    criteriaJson: {
      compositeKeys: ['final_rank', 'portfolio_complete', 'interview_complete'],
    },
    rewardJson: { coins: 2500, gems: 150, cosmetic: 'frame-job-ready' },
    sortOrder: 25,
  },
  {
    code: 'project-starter',
    name: 'Project Starter',
    description: 'Complete the first verified project task.',
    category: BadgeCategory.Projects,
    rarity: BadgeRarity.Common,
    iconAssetKey: 'project-starter',
    criteriaType: BadgeCriteriaType.Counter,
    criteriaJson: { counterKey: 'project_tasks_completed', target: 1 },
    rewardJson: { coins: 50 },
    sortOrder: 26,
  },
  {
    code: 'builder',
    name: 'Builder',
    description: 'Complete one full milestone project.',
    category: BadgeCategory.Projects,
    rarity: BadgeRarity.Uncommon,
    iconAssetKey: 'project-starter',
    criteriaType: BadgeCriteriaType.Counter,
    criteriaJson: { counterKey: 'projects_completed', target: 1 },
    rewardJson: { coins: 150, gems: 5 },
    sortOrder: 27,
  },
  {
    code: 'portfolio-hero',
    name: 'Portfolio Hero',
    description: 'Complete 3 portfolio-ready projects.',
    category: BadgeCategory.Projects,
    rarity: BadgeRarity.Epic,
    iconAssetKey: 'project-starter',
    criteriaType: BadgeCriteriaType.Counter,
    criteriaJson: { counterKey: 'portfolio_projects', target: 3 },
    rewardJson: { coins: 750, gems: 35 },
    sortOrder: 28,
  },
  {
    code: 'feedback-finisher',
    name: 'Feedback Finisher',
    description: 'Revise and pass final project review after feedback.',
    category: BadgeCategory.Projects,
    rarity: BadgeRarity.Rare,
    iconAssetKey: 'project-starter',
    criteriaType: BadgeCriteriaType.Counter,
    criteriaJson: { counterKey: 'project_reviews_passed', target: 1 },
    rewardJson: { coins: 250, gems: 10 },
    sortOrder: 29,
  },
  {
    code: 'study-buddy',
    name: 'Study Buddy',
    description: 'Complete the first qualified Study Together session.',
    category: BadgeCategory.Social,
    rarity: BadgeRarity.Common,
    iconAssetKey: 'weekly-warrior',
    criteriaType: BadgeCriteriaType.Counter,
    criteriaJson: { counterKey: 'study_sessions_qualified', target: 1 },
    rewardJson: { coins: 50 },
    sortOrder: 30,
  },
  {
    code: 'accountability-partner',
    name: 'Accountability Partner',
    description: 'Complete 10 Study Together sessions with 2+ friends.',
    category: BadgeCategory.Social,
    rarity: BadgeRarity.Uncommon,
    iconAssetKey: 'weekly-warrior',
    criteriaType: BadgeCriteriaType.Counter,
    criteriaJson: { counterKey: 'study_sessions_qualified', target: 10 },
    rewardJson: { coins: 200, gems: 10 },
    sortOrder: 31,
  },
  {
    code: 'learning-circle',
    name: 'Learning Circle',
    description: 'Study Together with 5 different friends.',
    category: BadgeCategory.Social,
    rarity: BadgeRarity.Rare,
    iconAssetKey: 'weekly-warrior',
    criteriaType: BadgeCriteriaType.DistinctSet,
    criteriaJson: { setKey: 'study_partners', setTarget: 5 },
    rewardJson: { coins: 300, gems: 15 },
    sortOrder: 32,
  },
  {
    code: 'first-victory',
    name: 'First Victory',
    description: 'Win the first eligible Battle.',
    category: BadgeCategory.Battle,
    rarity: BadgeRarity.Common,
    iconAssetKey: 'sql-spark',
    criteriaType: BadgeCriteriaType.Counter,
    criteriaJson: { counterKey: 'battle_wins', target: 1 },
    rewardJson: { coins: 50 },
    sortOrder: 33,
  },
  {
    code: 'battle-scholar',
    name: 'Battle Scholar',
    description: 'Win 20 Battles across 3+ subjects at 70%+ accuracy.',
    category: BadgeCategory.Battle,
    rarity: BadgeRarity.Rare,
    iconAssetKey: 'sql-spark',
    criteriaType: BadgeCriteriaType.Counter,
    criteriaJson: { counterKey: 'battle_wins', target: 20 },
    rewardJson: { coins: 400, gems: 20 },
    sortOrder: 34,
  },
  {
    code: 'connector',
    name: 'Connector',
    description: 'Reach 5 qualified referrals.',
    category: BadgeCategory.Referral,
    rarity: BadgeRarity.Uncommon,
    iconAssetKey: 'first-step',
    criteriaType: BadgeCriteriaType.ReferralMilestone,
    criteriaJson: { referralQualified: 5 },
    rewardJson: { skipLedger: true },
    sortOrder: 35,
  },
  {
    code: 'arc-ambassador',
    name: 'Arc Ambassador',
    description: 'Reach 25 qualified referrals.',
    category: BadgeCategory.Referral,
    rarity: BadgeRarity.Epic,
    iconAssetKey: 'job-ready-eagle',
    criteriaType: BadgeCriteriaType.ReferralMilestone,
    criteriaJson: { referralQualified: 25 },
    rewardJson: { skipLedger: true },
    sortOrder: 36,
  },
];
